easy_admin:
    entities:
        Category:
            class: App\Entity\Category
            label: 'Category Management'
            list:
                title: "Category List"
                actions:
                    - { name: 'show', icon: 'search' }
                    - { name: 'edit', icon: 'pencil' }
                    - { name: 'delete', icon: 'trash' }
