easy_admin:
    entities:
        Page:
            class: App\Entity\Page
            label: 'Page Management'
            list:
                title: "Page List"
                actions:
                    - { name: 'show', icon: 'search' }
                    - { name: 'edit', icon: 'pencil' }
                    - { name: 'delete', icon: 'trash' }

            new:
                fields:
                    - 'title'
                    - { property: 'content', css_class: 'ckeditor5', type_options: { required: false } }
                    - 'date'
                    - 'is_published'

            edit:
                fields:
                    - 'title'
                    - { property: 'content', css_class: 'ckeditor5', type_options: { required: false } }
                    - 'date'
                    - 'is_published'
