easy_admin:
    entities:
        Post:
            class: App\Entity\Post
            label: 'Post Management'
            list:
                title: "Post List"
                actions:
                    - { name: 'show', icon: 'search' }
                    - { name: 'edit', icon: 'pencil' }
                    - { name: 'delete', icon: 'trash' }

            new:
                fields:
                    - 'title'
                    - { property: 'content', css_class: 'ckeditor5', type_options: { required: false } }
                    - 'date'
                    - 'is_published'
                    - 'category'
                    - 'tags'

            edit:
                fields:
                    - 'title'
                    - { property: 'content', css_class: 'ckeditor5', type_options: { required: false } }
                    - 'date'
                    - 'is_published'
                    - 'category'
                    - 'tags'
