easy_admin:
    entities:
        Project:
            class: App\Entity\Project
            label: 'Project Management'
            list:
                title: "Project List"
                actions:
                    - { name: 'show', icon: 'search' }
                    - { name: 'edit', icon: 'pencil' }
                    - { name: 'delete', icon: 'trash' }
