easy_admin:
    entities:
        Tag:
            class: App\Entity\Tag
            label: 'Tag Management'
            list:
                title: "Tag List"
                actions:
                    - { name: 'show', icon: 'search' }
                    - { name: 'edit', icon: 'pencil' }
                    - { name: 'delete', icon: 'trash' }
