easy_admin:
    entities:
        User:
            class: App\Entity\User
            label: 'User Management'
            password_encoding: { algorithm: 'bcrypt', cost: 12 }
            list:
                title: "User List"
                actions:
                    - { name: 'show', icon: 'search' }
                    - { name: 'edit', icon: 'pencil' }
                    - { name: 'delete', icon: 'trash' }

            new:
                fields:
                    - 'username'
                    - { property: 'password', type: 'password' }
                    - 'email'
                    - 'is_active'

            edit:
                fields:
                    - 'username'
                    - { property: 'password', type: 'password' }
                    - 'email'
                    - 'is_active'
