easy_admin:
    site_name: 'Papirus Admin'
    design:
        assets:
            js:
              - 'assets/tinymce/tinymce.min.js'
              - 'assets/admin/custom.js'
    user:
        name_property_path: 'username'