easy_admin:
    design:
        menu:
            - { entity: 'Page', icon: 'file' }
            - { entity: 'Post', icon: 'pencil' }
            - { entity: 'Category', icon: 'folder' }
            - { entity: 'Tag', icon: 'tags' }
            - { entity: 'Project', icon: 'briefcase' }
            - { entity: 'User', icon: 'user' }
            - { entity: 'Setting', icon: 'gear' }
